const REMAPPING_NNDSS = {
    "10350": {name: "Anthrax", category: "Bacterial"},
    "10073": {name: "Chikungunya virus", category: "Viral"},
    "10053": {name: "Eastern equine encephalitis virus", category: "Viral"},
    "10078": {name: "Jamestown Canyon virus", category: "Viral"},
    "10079": {name: "Jamestown Canyon virus", category: "Viral"},
    "10080": {name: "Jamestown Canyon virus", category: "Viral"},
    "10081": {name: "La Crosse virus", category: "Viral"},
    "10082": {name: "La Crosse virus", category: "Viral"},
    "10057": {name: "Powassan virus", category: "Viral"},
    "10063": {name: "Powassan virus", category: "Viral"},
    "10051": {name: "St. Louis encephalitis virus", category: "Viral"},
    "10064": {name: "St. Louis encephalitis virus", category: "Viral"},
    "10056": {name: "West Nile virus", category: "Viral"},
    "10049": {name: "West Nile virus", category: "Viral"},
    "12010": {name: "Babesiosis", category: "Parasitic"},
    "12011": {name: "Babesiosis", category: "Parasitic"},
    "12012": {name: "Babesiosis", category: "Parasitic"},
    "10360": {name: "Botulism", category: "Bacterial"},
    "10530": {name: "Botulism", category: "Bacterial"},
    "10540": {name: "Botulism", category: "Bacterial"},
    "10550": {name: "Botulism", category: "Bacterial"},
    "10020": {name: "Brucellosis", category: "Bacterial"},
    "11020": {name: "Campylobacteriosis", category: "Bacterial"},
    "50263": {name: "Candida auris, clinical", category: "Fungal"},
    "50244": {name: "Enterobacteriaceae", category: "Bacterial"},
    "10273": {name: "Chancroid", category: "Bacterial"},
    "10274": {name: "Chlamydia", category: "Bacterial"},
    "10470": {name: "Cholera", category: "Bacterial"},
    "11900": {name: "Coccidioidomycosis", category: "Fungal"},
    "11065": {name: "COVID-19", category: "Viral"},
    "11067": {name: "COVID-19", category: "Viral"},
    "11068": {name: "COVID-19", category: "Viral"},
    "11580": {name: "Cryptosporidiosis", category: "Parasitic"},
    "11582": {name: "Cryptosporidiosis", category: "Parasitic"},
    "11583": {name: "Cryptosporidiosis", category: "Parasitic"},
    "11575": {name: "Cyclosporiasis", category: "Parasitic"},
    "10680": {name: "Dengue virus", category: "Viral"},
    "11704": {name: "Dengue-like illness", category: "Viral"},
    "11705": {name: "Severe dengue", category: "Viral"},
    "10040": {name: "Diphtheria", category: "Bacterial"},
    "11090": {name: "Anaplasma phagocytophilum", category: "Bacterial"},
    "11088": {name: "Ehrlichia chaffeensis", category: "Bacterial"},
    "11089": {name: "Ehrlichia ewingii", category: "Bacterial"},
    "11091": {name: "Undetermined ehrlichiosis/anaplasmosis", category: "Bacterial"},
    "11570": {name: "Giardiasis", category: "Parasitic"},
    "10280": {name: "Gonorrhea", category: "Bacterial"},
    "10590": {name: "Haemophilus influenza", category: "Bacterial"},
    "10591": {name: "Haemophilus influenza", category: "Bacterial"},
    "10593": {name: "Haemophilus influenza", category: "Bacterial"},
    "10592": {name: "Haemophilus influenza", category: "Bacterial"},
    "10594": {name: "Haemophilus influenza", category: "Bacterial"},
    "10380": {name: "Hansen's disease", category: "Bacterial"},
    "11610": {name: "Hantavirus infection", category: "Viral"},
    "11590": {name: "Hantavirus pulmonary syndrome", category: "Viral"},
    "11550": {name: "Hemolytic uremic syndrome", category: "Bacterial"},
    "10110": {name: "Hepatitis A", category: "Viral"},
    "10100": {name: "Hepatitis B", category: "Viral"},
    "10104": {name: "Hepatitis B, perinatal infection", category: "Viral"},
    "10101": {name: "Hepatitis C", category: "Viral"},
    "50228": {name: "Hepatitis C", category: "Viral"},
    "50229": {name: "Hepatitis C", category: "Viral"},
    "50248": {name: "Hepatitis C", category: "Viral"},
    "10560": {name: "Human immunodeficiency virus", category: "Viral"},
    "11061": {name: "Influenza-associated pediatric mortality", category: "Viral"},
    "11723": {name: "Invasive pneumococcal disease", category: "Bacterial"},
    "50230": {name: "Invasive pneumococcal disease", category: "Bacterial"},
    "50231": {name: "Invasive pneumococcal disease", category: "Bacterial"},
    "11722": {name: "Invasive pneumococcal disease", category: "Bacterial"},
    "50232": {name: "Invasive pneumococcal disease", category: "Bacterial"},
    "50233": {name: "Invasive pneumococcal disease", category: "Bacterial"},
    "10490": {name: "Legionellosis", category: "Bacterial"},
    "10390": {name: "Leptospirosis", category: "Bacterial"},
    "10640": {name: "Listeriosis", category: "Bacterial"},
    "10641": {name: "Listeriosis", category: "Bacterial"},
    "10642": {name: "Listeriosis", category: "Bacterial"},
    "11080": {name: "Lyme disease", category: "Bacterial"},
    "11081": {name: "Lyme disease", category: "Bacterial"},
    "11082": {name: "Lyme disease", category: "Bacterial"},
    "10130": {name: "Malaria", category: "Parasitic"},
    "10140": {name: "Measles", category: "Viral"},
    "10500": {name: "Measles", category: "Viral"},
    "10510": {name: "Measles", category: "Viral"},
    "10150": {name: "Meningococcal disease", category: "Bacterial"},
    "10151": {name: "Meningococcal disease", category: "Bacterial"},
    "10152": {name: "Meningococcal disease", category: "Bacterial"},
    "10153": {name: "Meningococcal disease", category: "Bacterial"},
    "10154": {name: "Meningococcal disease", category: "Bacterial"},
    "10180": {name: "Mumps", category: "Viral"},
    "11062": {name: "Novel Influenza A virus", category: "Viral"},
    "50236": {name: "Paratyphoid fever", category: "Bacterial"},
    "10190": {name: "Pertussis", category: "Bacterial"},
    "10440": {name: "Plague", category: "Bacterial"},
    "10450": {name: "Psittacosis", category: "Bacterial"},
    "10256": {name: "Q fever", category: "Bacterial"},
    "10257": {name: "Q fever", category: "Bacterial"},
    "10258": {name: "Q fever", category: "Bacterial"},
    "10340": {name: "Rabies, animal", category: "Viral"},
    "10460": {name: "Rabies, human", category: "Viral"},
    "10200": {name: "Rubella", category: "Viral"},
    "10370": {name: "Rubella", category: "Viral"},
    "50266": {name: "Salmonella Paratyphi infection", category: "Bacterial"},
    "50267": {name: "Salmonella Typhi infection", category: "Bacterial"},
    "11000": {name: "Salmonellosis", category: "Bacterial"},
    "50242": {name: "Salmonellosis", category: "Bacterial"},
    "50265": {name: "Salmonellosis", category: "Bacterial"},
    "11563": {name: "STEC", category: "Bacterial"},
    "11010": {name: "Shigellosis", category: "Bacterial"},
    "10250": {name: "Spotted fever rickettsiosis, Total", category: "Bacterial"},
    "10253": {name: "Spotted fever rickettsiosis, Confirmed", category: "Bacterial"},
    "10254": {name: "Spotted fever rickettsiosis, Probable", category: "Bacterial"},
    "11700": {name: "Streptococcal toxic shock syndrome", category: "Bacterial"},
    "10399": {name: "Syphilis", category: "Bacterial"},
    "10316": {name: "Syphilis, Congenital", category: "Bacterial"},
    "10310": {name: "Syphilis, Primary and secondary", category: "Bacterial"},
    "10210": {name: "Tetanus", category: "Bacterial"},
    "10520": {name: "Toxic shock syndrome", category: "Bacterial"},
    "10270": {name: "Trichinellosis", category: "Parasitic"},
    "10220": {name: "Tuberculosis", category: "Bacterial"},
    "10230": {name: "Tularemia", category: "Bacterial"},
    "10240": {name: "Typhoid fever", category: "Bacterial"},
    "11663": {name: "Vancomycin-intermediate Staphylococcus aureus", category: "Bacterial"},
    "11665": {name: "Vancomycin-resistant Staphylococcus aureus", category: "Bacterial"},
    "10030": {name: "Varicella morbidity", category: "Viral"},
    "10031": {name: "Varicella mortality", category: "Viral"},
    "11545": {name: "Vibriosis, Total", category: "Bacterial"},
    "50234": {name: "Vibriosis, Confirmed", category: "Bacterial"},
    "50235": {name: "Vibriosis, Probable", category: "Bacterial"},
    "10660": {name: "Yellow fever", category: "Viral"},
    "50224": {name: "Zika virus disease", category: "Viral"},
    "50223": {name: "Zika virus disease", category: "Viral"},
    "50222": {name: "Zika virus infection", category: "Viral"},
    "50221": {name: "Zika virus infection", category: "Viral"},
}